name: reca_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  shared_preferences: ^2.0.11
  carousel_pro_nullsafety: ^1.0.2
  timeago: ^3.1.0
  flutter_expandable: ^1.0.0
  expandable_widget: ^2.0.0-nullsafety
  http: ^0.13.4
  shimmer: ^2.0.0
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.18
  image_picker: ^0.8.4+4
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  like_button: ^2.0.4
  expandable_page_view: ^1.0.10
  font_awesome_flutter: ^9.2.0
  flutter_custom_clippers: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3

flutter_native_splash:
  color: "#f7921f"
  image: "assets/images/reca logo2.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/girl.png
